name: CI

on:
  workflow_dispatch:
    inputs:
      json_string:
        required: true
        type: string
        default: '{"name": "John Doe", "age": 30, "city": "New York", "email": "johndoe@example.com", "is_employee": true, "hobbies": ["reading", "hiking", "photography"], "address": {"street": "123 Main St", "city": "New York", "zipcode": "10001", "country": "USA"}}'

jobs:
  convert_string_to_list:
    runs-on: ubuntu-latest
    steps:
      - name: Create an array of args
        id: args
        run: echo "::set-output name=build_args::$(jq 'split(",")' -Rc <(echo '${{ inputs.build_args }}'))"

        
      - name: Create list of modified files
        id: modified_files_list
        uses: lucaspinheirogit/list-from-string-array-action@v1.4.3
        with:
          stringArray: ${{ steps.args.outputs.build_args }}

      - name: Print modified files
        run: echo '${{ steps.modified_files_list.outputs.stringList }}'
