name: CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]
  workflow_dispatch:
    inputs:
      json_string:
        required: true
        type: string
        default: '{"name": "John Doe", "age": 30, "city": "New York", "email": "johndoe@example.com", "is_employee": true, "hobbies": ["reading", "hiking", "photography"], "address": {"street": "123 Main St", "city": "New York", "zipcode": "10001", "country": "USA"}}'

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: Set JSON string
        id: set-json
        run: echo "::set-output name=json_string::${{ inputs.json_string }}"
        shell: bash
        env:
          inputs.json_string: ${{ toJson(inputs.json_string) }}

      - name: Parse JSON string into array
        id: parse-json
        run: echo "${{ steps.set-json.outputs.json_string }}" | jq -r '.hobbies[]'
        shell: bash

      - name: Create list of modified files
        id: modified_files_list
        uses: lucaspinheirogit/list-from-string-array-action@v1.4.3
        with:
          stringArray: ${{ steps.parse-json.outputs.stdout }}
          
      - name: Print modified files
        run: echo '${{ steps.modified_files_list.outputs.stringList }}'
