name: CI

on:
  workflow_dispatch:
    inputs:
      json_string:
        required: true
        type: string
        default: '{"name": "John Doe", "age": 30, "city": "New York", "email": "johndoe@example.com", "is_employee": true, "hobbies": ["reading", "hiking", "photography"], "address": {"street": "123 Main St", "city": "New York", "zipcode": "10001", "country": "USA"}}'

jobs:
  convert_string_to_list:
    runs-on: ubuntu-latest
    steps:
      - name: Set JSON string
        id: set-json
        run: echo "::set-output name=json_string::${{ inputs.json_string }}"
        shell: bash
        env:
          inputs.json_string: ${{ toJson(inputs.json_string) }}
          
      - name: Convert JSON string to list
        id: convert-json
        run: echo "::set-output name=json_list::${{ fromJson(steps.set-json.outputs.json_string).items }}"
        shell: bash
        
      - name: Print list
        run: echo "${{ steps.convert-json.outputs.json_list }}"
