name: CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]
  workflow_dispatch:
    inputs:
      json_string:
        required: true
        type: string
        default: '{"name": "John Doe", "age": 30, "city": "New York", "email": "johndoe@example.com", "is_employee": true, "hobbies": ["reading", "hiking", "photography"], "address": {"street": "123 Main St", "city": "New York", "zipcode": "10001", "country": "USA"}}'

jobs:
  convert_string_to_list:
    runs-on: ubuntu-latest
    steps:
      - name: Set the string value
        run: echo "::set-output name=my_string::apple,banana,orange"

      - name: Convert string to list
        id: convert
        run: echo "::set-output name=my_list::$(echo ${{ steps.set_string.outputs.my_string }} | tr ',' '\n')"
        shell: bash

      - name: Print the converted list
        run: echo "My list is ${{ steps.convert.outputs.my_list }}"
